name: setup-lint-test
# действие на которое запускается workflow
on: push

jobs:
  # имя задания
  say-hello:
    # OC для запуска
    runs-on: ubuntu-latest
    # шаги, которые надо выполнить
    steps:
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      # установка node.js
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      # install npm and build project
      - run: make setup
      # run linter
      - run: make lint
      # run tests
      - run: make test
      # run sync check
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high